# Generated by Django 4.2.24 on 2025-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('echonomic_code', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('allocation', models.IntegerField()),
                ('achivement', models.CharField(blank=True, max_length=255, null=True)),
                ('requirement', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Budget',
            },
        ),
    ]
