# Generated by Django 4.2.24 on 2025-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Personal_info',
            },
        ),
    ]
