# Generated by Django 4.2.24 on 2025-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Center_id', models.IntegerField()),
                ('Course_id', models.IntegerField()),
                ('Fiscal_year', models.DateTimeField()),
                ('Participant_target', models.IntegerField()),
                ('Course_target', models.IntegerField()),
                ('Proposed_start_date', models.DateTimeField()),
                ('Proposed_end_date', models.DateTimeField()),
                ('Actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('Actual_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Batch_table',
            },
        ),
    ]
