# Generated by Django 5.2.7 on 2025-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_batch_center_id_alter_batch_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Fiscal_year',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
