# Generated by Django 4.2.24 on 2025-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Center_id', models.IntegerField()),
                ('Course_name', models.CharField(max_length=255)),
                ('Course_duration', models.CharField(max_length=255)),
                ('Batch_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Course_table',
            },
        ),
    ]
