# Generated by Django 4.2.24 on 2025-09-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Center_name', models.CharField(max_length=255)),
                ('Establishment_year', models.DateTimeField()),
                ('District', models.CharField(max_length=255)),
                ('RD_office', models.CharField(max_length=255)),
                ('Officer_in_charge', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Center',
            },
        ),
    ]
